//! Account creation and client-folder staging.
//!
//! Creating an account has two side effects that must stay consistent: a line
//! in the accounts file (`CLIENTS_PATH`) and a staged client folder under
//! `$STATE_DIR/client-ready/<name>`. Every check that can fail runs before the
//! accounts file changes, and a later failure rolls both back best-effort, so
//! `create` never leaves a half-created account behind.

pub mod clients;

use std::fmt::Write as _;
use std::net::IpAddr;
use std::path::{Path, PathBuf};

use crate::access::Access;
use crate::config::Config;
use crate::error::{Error, Result};
use crate::policy;

use self::clients::{Account, Clients};

/// The result of a successful account creation.
#[derive(Debug)]
pub struct Created {
    /// Directory holding the staged client folder.
    pub staging: PathBuf,
}

/// Create an account and stage its client folder.
///
/// The account name, the access policy, the staged client bundle, and the TLS
/// certificate are validated before the accounts file is written. If staging
/// fails afterwards, the account line and the staging directory are removed.
pub fn create(
    config: &Config,
    name: &str,
    ip: Option<IpAddr>,
    output: &Path,
    local: bool,
) -> Result<Created> {
    let mut accounts = Clients::load(&config.clients_path)?;
    if accounts.get(name).is_some() {
        return Err(Error::Account(format!("account {name} already exists")));
    }

    let pull_source = config.bundle_dir().join("pull.py");
    if !pull_source.is_file() {
        return Err(Error::Config(
            "client bundle not staged; run 'sudo lanpull init' or reinstall".to_string(),
        ));
    }

    let policy = policy::Policy::load(&config.access_path)?;
    if !policy.has_effective_rules(name) {
        return Err(Error::Account(format!(
            "account {name} has no access; grant it with \
             'sudo lanpull access public add <share>:**' first"
        )));
    }
    if !config.cert_path.is_file() {
        return Err(Error::Certificate(format!(
            "no certificate at {}; run 'lanpull cert' first",
            config.cert_path.display()
        )));
    }

    let password = clients::generate_password();
    let hash = clients::hash_password(&password)?;
    accounts.insert(Account {
        name: name.to_string(),
        hash,
        allowed_ip: ip,
        local,
    });
    accounts.save(&config.clients_path)?;

    // The account now exists, so the policy expands with its `public` rules.
    let access = policy::load_access(config)?;

    let staging = config.state_dir.join("client-ready").join(name);
    if let Err(e) = stage(
        config,
        name,
        output,
        &access,
        &password,
        &pull_source,
        &staging,
    ) {
        rollback(config, name, &staging);
        return Err(e);
    }

    Ok(Created { staging })
}

/// Write the staged client folder for a freshly created account.
fn stage(
    config: &Config,
    name: &str,
    output: &Path,
    access: &Access,
    password: &str,
    pull_source: &Path,
    staging: &Path,
) -> Result<()> {
    std::fs::create_dir_all(staging)?;

    std::fs::copy(pull_source, staging.join("pull.py"))?;
    set_executable(&staging.join("pull.py"))?;

    std::fs::write(
        staging.join("lanpull.conf"),
        client_conf(config, name, output, access)?,
    )?;
    let auth = format!("{name}:{password}\n");
    crate::atomic::write_private(&staging.join("auth"), auth.as_bytes())?;
    std::fs::copy(&config.cert_path, staging.join("server.crt"))?;
    Ok(())
}

/// Best-effort reversal of a partially applied [`create`].
fn rollback(config: &Config, name: &str, staging: &Path) {
    if let Err(e) = std::fs::remove_dir_all(staging) {
        if e.kind() != std::io::ErrorKind::NotFound {
            tracing::warn!("could not remove staging {}: {e}", staging.display());
        }
    }

    let mut accounts = match Clients::load(&config.clients_path) {
        Ok(accounts) => accounts,
        Err(e) => {
            tracing::warn!("could not roll back account {name}: {e}");
            return;
        }
    };
    if accounts.remove(name) {
        if let Err(e) = accounts.save(&config.clients_path) {
            tracing::warn!("could not roll back account {name}: {e}");
        }
    }
}

/// Build the staged client config mapping each visible share to a subdirectory.
pub fn client_conf(
    config: &Config,
    account: &str,
    output: &Path,
    access: &Access,
) -> Result<String> {
    let mut text = format!(
        "# Generated by lanpull add-client for {account}.\nSERVER_URL=https://{}:{}\n",
        config.server_ip, config.port
    );
    for share in config.shares.keys() {
        if access.allows_share(account, share) {
            let _ = writeln!(text, "MIRROR_{share}={}", output.join(share).display());
        }
    }
    Ok(text)
}

/// Mark a file executable (mode 0755).
fn set_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut permissions = std::fs::metadata(path)?.permissions();
    permissions.set_mode(0o755);
    std::fs::set_permissions(path, permissions)?;
    Ok(())
}
