//! `lanpull init` — create the configuration and state for this machine.
//!
//! Replaces the former `init-config.sh`: it derives the LAN address from the
//! routing table, prompts for the remaining values, creates the share and state
//! directories, and writes the configuration file (mode 0600).

use std::io::{BufRead as _, IsTerminal as _, Write as _};
use std::net::IpAddr;
use std::path::{Path, PathBuf};

use lanpull_core::config as core_config;
use lanpull_core::error::{Error, Result};

use crate::cli::share::InitArgs;

/// Run `lanpull init`.
pub fn run(config_path: &Path, args: &InitArgs) -> Result<()> {
    use std::fmt::Write as _;

    let config_dir = config_path.parent().unwrap_or_else(|| Path::new("."));

    let shares = resolve_shares(&args.shares)?;
    let state_dir = args
        .state_dir
        .clone()
        .unwrap_or_else(|| PathBuf::from(core_config::DEFAULT_STATE_DIR));
    let bind = args
        .bind
        .clone()
        .unwrap_or_else(|| core_config::DEFAULT_BIND.to_string());
    let port = args.port.unwrap_or(core_config::DEFAULT_PORT);
    let server_ip = match &args.server_ip {
        Some(value) => value
            .parse::<IpAddr>()
            .map_err(|e| Error::Config(format!("SERVER_IP: {e}")))?,
        None => detect_server_ip()?,
    };

    if config_path.exists() && !args.non_interactive {
        return Err(Error::Config(format!(
            "{} already exists; remove it or pass --non-interactive",
            config_path.display()
        )));
    }

    std::fs::create_dir_all(config_dir)?;
    for (_, dir) in &shares {
        if !dir.is_dir() {
            std::fs::create_dir_all(dir)?;
        }
    }
    create_state_dir(&state_dir)?;

    let mut text = String::new();
    text.push_str("# lanpull server configuration.\n");
    text.push_str("# Generated by 'lanpull init'. Mode 600; not committed.\n\n");
    for (name, dir) in &shares {
        let _ = writeln!(text, "SHARE_{name}={}", dir.display());
    }
    let _ = writeln!(text, "STATE_DIR={}", state_dir.display());
    let _ = writeln!(text, "BIND={bind}");
    let _ = writeln!(text, "PORT={port}");
    let _ = writeln!(text, "SERVER_IP={server_ip}");
    let _ = writeln!(text, "CERT_PATH={}", state_dir.join("server.crt").display());
    let _ = writeln!(text, "KEY_PATH={}", state_dir.join("server.key").display());
    text.push_str("CLIENTS_PATH=lanpull.clients\n");
    text.push_str("ACCESS_PATH=lanpull.access.json\n");
    let _ = writeln!(text, "AUDIT_LOG={}", state_dir.join("access.log").display());

    lanpull_core::atomic::write_private(config_path, text.as_bytes())?;
    // Validate before reporting success.
    core_config::Config::load(config_path)?;

    println!("wrote {}", config_path.display());
    println!("  STATE_DIR={}", state_dir.display());
    println!("  SERVER_IP={server_ip}");
    Ok(())
}

/// Parse `name=path` share specifications, defaulting to a single `default`.
fn resolve_shares(specs: &[String]) -> Result<Vec<(String, PathBuf)>> {
    if specs.is_empty() {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/home".to_string());
        return Ok(vec![(
            "default".to_string(),
            PathBuf::from(home).join("lanpull-share"),
        )]);
    }
    let mut shares = Vec::new();
    for spec in specs {
        let (name, path) = spec
            .split_once('=')
            .ok_or_else(|| Error::Config(format!("invalid --share {spec}: expected name=path")))?;
        if !core_config::valid_share_name(name) {
            return Err(Error::Config(format!(
                "invalid share name {name}: must match ^[a-z0-9][a-z0-9_-]*$"
            )));
        }
        shares.push((name.to_string(), PathBuf::from(path)));
    }
    Ok(shares)
}

/// Create the state directory, escalating to sudo when needed.
fn create_state_dir(state_dir: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt as _;
    if state_dir.is_dir() {
        return Ok(());
    }
    if let Some(parent) = state_dir.parent() {
        if parent.exists() {
            std::fs::create_dir_all(state_dir)?;
            std::fs::set_permissions(state_dir, std::fs::Permissions::from_mode(0o700))?;
            return Ok(());
        }
    }
    Err(Error::Config(format!(
        "cannot create {}; create it as root with mode 700",
        state_dir.display()
    )))
}

/// Detect the host's private LAN address from the main routing table.
fn detect_server_ip() -> Result<IpAddr> {
    let output = std::process::Command::new("ip")
        .args(["-4", "route", "show", "default"])
        .output()
        .map_err(|e| Error::Config(format!("could not run 'ip': {e}")))?;
    let text = String::from_utf8_lossy(&output.stdout);
    for line in text.lines() {
        let mut fields = line.split_whitespace();
        while let Some(field) = fields.next() {
            if field == "src" {
                if let Some(addr) = fields.next() {
                    if let Ok(ip) = addr.parse::<IpAddr>() {
                        return Ok(ip);
                    }
                }
            }
        }
    }
    Err(Error::Config(
        "could not detect the LAN address; pass --server-ip".to_string(),
    ))
}

/// Read a line from the terminal, or return the default when non-interactive.
#[allow(dead_code)]
fn prompt(default: &str, label: &str, interactive: bool) -> String {
    if !interactive || !std::io::stdin().is_terminal() {
        return default.to_string();
    }
    eprint!("{label} [{default}]: ");
    let _ = std::io::stderr().flush();
    let mut line = String::new();
    if std::io::stdin().lock().read_line(&mut line).is_err() {
        return default.to_string();
    }
    let value = line.trim();
    if value.is_empty() {
        default.to_string()
    } else {
        value.to_string()
    }
}
